### ISSUE TITLE
同学们的福利

### ISSUE THREAD

**Issue by Liyunfan1998** [Liyunfan1998/ics_TA#3]
如果实在难以完成本次lab，可以直接抄Mult函数实现 **给50分**

**Comment by huangxuanming** [comment]
万一我自己写的还没有50分怎么办？

**Comment by Liyunfan1998** [comment]
同学们在涉及这些不正经的东西的时候不要随意放在唐老师可见的地方，否则福利什么的可能会被取缔哦~

**Comment by Liyunfan1998** [comment]
### 郑重申明，本次lab最终解释权归“ics助教老师小组”所有
